title: Luis Tapia
email: lmtapia1024@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
   Luis Tapia is a developer and musician from Bolivia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  luismtapiab
lang: en-US
# Build settings
theme: minima
plugins:
  - jekyll-feed

minima: 
  skin: dark
show_excerpts: true